name: e2e-tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compose up (build + run tests)
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from tests

      - name: Compose down (cleanup)
        if: always()
        run: docker compose down -v

